### ISSUE TITLE
Video duration filter did not work

### ISSUE THREAD

**Issue by gkibria69** [pluginever/wp-content-pilot#59]
[The selected video duration](https://i.imgur.com/2iF8wuC.png) did not work. Published a video shorter than the selected filter.

**Comment by sudipto-me** [comment]
Youtube videos duration short and long is working. But medium is not working.

**Comment by sudipto-me** [comment]
It happens when the campaign finds existing links in the database table. If no links found in the database then it will find new links from the API.
