### ISSUE TITLE
Error Message : Could Not retrieve any valid links

### ISSUE THREAD

**Issue by aganuphi** [pluginever/wp-content-pilot#6]
Hi All,
I have issue when running a test campaign on all campaign type ( feed, Article, etc ). There always appear pop up message " could not retrieve any valid links". ( the screenshot is attached )

Please help...

Thanks

Best regards
Agan
![wp content pilot error](https://user-images.githubusercontent.com/38425527/40402437-d0ad2cb0-5e75-11e8-9646-ec549a520c88.jpg)

![image](https://user-images.githubusercontent.com/38425527/40402316-22e2fcfe-5e75-11e8-8db1-074c9756d805.png)

**Comment by sultann** [comment]
@aganuphi 
We have worked a lot on the plugin to make it workable.
Can you please try install a fresh version of the plugin.
or try a demo from here http://wpcp.pluginever.com/wp-admin/
