### ISSUE TITLE
Options for random and ordered post fetching

### ISSUE THREAD

**Issue by adnanalneon** [pluginever/wp-content-pilot#84]
Suppose, An Instagram user has 35 posts. An user starts an Instagram campaign. The campaign will pull 35th posts and it will not fetch any other posts until 36th post will be published, then 37th and so on. The target is to fetch all the latest posts onward. We will also be needing an option to fetch posts randomly. e.g. 35th, 7th, 19th and so on. (Current version fetches posts randmly)

The options should be:

- Fetch only latest posts onward
- Fetch posts randomly

**Comment by sudipto-me** [comment]
We have added fetching latest posts options.

**Comment by sudipto-me** [comment]
We have added fetching latest posts options.
